# Generated by Django 3.2.6 on 2021-09-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0003_rename_words_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word_sta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=200)),
                ('levels', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Word',
            new_name='Word_gen',
        ),
    ]
